### ISSUE TITLE
Error when doing large directory scans

### ISSUE THREAD

**Issue by IamManifold** [gliviu/dir-compare#22]
I'm basically trying to make a directory compare tool that list all the files that are different between two directories. I can share my code if it helps. 

```
Error: UNKNOWN: unknown error, lstat 'M:\User\xx\Node Projects\next-learn-demo\3-create-dynamic-pages\node_modules\core-js\fn\object\define.js'
    at Object.lstatSync (fs.js:943:3)
    at getStatIgnoreBrokenLink (C:\Node\fileDiff\node_modules\dir-compare\src\entry\entryBuilder.js:50:17)
    at Object.buildEntry (C:\Node\fileDiff\node_modules\dir-compare\src\entry\entryBuilder.js:32:15)
    at Object.buildDirEntries (C:\Node\fileDiff\node_modules\dir-compare\src\entry\entryBuilder.js:19:21)
    at C:\Node\fileDiff\node_modules\dir-compare\src\compareAsync.js:21:37
    at async Promise.all (index 1)
    at async Promise.all (index 9)
    at async Promise.all (index 6)
    at async Promise.all (index 92)
    at async Promise.all (index 3) {
  errno: -2146893818,
  syscall: 'lstat',
  code: 'UNKNOWN',
  path: 'M:\\User\\xx\\Node Projects\\next-learn-demo\\3-create-dynamic-pages\\node_modules\\core-js\\fn\\object\\define.js'
}
```

**Comment by gliviu** [comment]
Looks related to the way windows handles symlinks when using network drives or WSL.
Possible fixes below.
https://github.com/bmewburn/vscode-intelephense/issues/260#issuecomment-488674630
https://github.com/mrmlnc/fast-glob/issues/161
https://stackoverflow.com/questions/29004843/unknown-error-on-package-installation

**Comment by IamManifold** [comment]
Thanks, I"m going to look into those fixes to see if it works. 

I seem to be getting a handful of different errors during my test scans. 
I think i'm going to work on the rest of my process and just test with smaller directories until i can figure out what's going on.


Error: EMFILE: too many open files, open 'C:\justin.miller\Code\''Working'' code\VexcelDemo 4-5-2019\node_modules\forwarded\HISTORY.md'
    at Object.openSync (fs.js:461:3)
    at Object.fileBufferObject (C:\Node\fileDiff\node_modules\filecompare\lib\index.js:6:17)
    at compare (C:\Node\fileDiff\node_modules\filecompare\index.js:8:16)
    at C:\Node\fileDiff\app.js:90:17
    at Array.forEach (<anonymous>)
    at print (C:\Node\fileDiff\app.js:50:20)
    at C:\Node\fileDiff\app.js:30:18 {
  errno: -4066,
  syscall: 'open',
  code: 'EMFILE',
  path: "C:\\justin.miller\\Code\\''Working'' code\\VexcelDemo 4-5-2019\\node_modules\\forwarded\\HISTORY.md"
}

**Comment by gliviu** [comment]
Yes, it is possible. If you use `compareContent: true` option, it will check the files content, disregarding size of file.
