### ISSUE TITLE
Issue regarding non-redable files

### ISSUE THREAD

**Issue by moshfeu** [gliviu/dir-compare#37]
```shell
mkdir -p tmp/test1.good
mkdir -p tmp/test2.good
mkdir -p tmp/test3.bad
touch tmp/test1.good/test.txt
touch tmp/test2.good/test.txt
touch tmp/test3.bad/test.txt
sudo chown root:root tmp/test3.bad/ -R
sudo chmod og= tmp/test3.bad/
cd tmp/
npm install dir-compare-cli
./node_modules/.bin/dircompare test1.good test2.good
```

Entries are identical
total: 1, equal: 1, distinct: 0, only left: 0, only right: 0

```
./node_modules/.bin/dircompare test1.good test3.bad

Error occurred: Error: EACCES: permission denied, scandir '/home/joseph/tmp/test3.bad'
at Object.readdirSync (fs.js:981:3)
at getEntries (/home/joseph/tmp/node_modules/dir-compare-cli/node_modules/dir-compare/src/compareSync.js:18:26)
at compare (/home/joseph/tmp/node_modules/dir-compare-cli/node_modules/dir-compare/src/compareSync.js:33:20)
at Object.compareSync (/home/joseph/tmp/node_modules/dir-compare-cli/node_modules/dir-compare/src/index.js:27:5)
at /home/joseph/tmp/node_modules/dir-compare-cli/src/cli/dircompare.js:113:44
at new Promise ()
at run (/home/joseph/tmp/node_modules/dir-compare-cli/src/cli/dircompare.js:112:38)
at Object. (/home/joseph/tmp/node_modules/dir-compare-cli/src/cli/dircompare.js:147:1)
at Module._compile (internal/modules/cjs/loader.js:1075:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
```

Copied from https://github.com/moshfeu/vscode-compare-folders/issues/71#issuecomment-821961418

**Comment by gliviu** [comment]
Added commend in vscode-compare-folders issue.
